hostname router-c
!
interface eth0
 ip address 10.0.23.2/30
 ipv6 address 2001:db8:23::2/64
!
router bgp 65003
 bgp router-id 10.0.23.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 2001:db8:23::1 remote-as 65002
 !
 address-family ipv6 unicast
  network 2001:db8:3::/48
  neighbor 2001:db8:23::1 activate
 exit-address-family
!
line vty
!
