hostname pe2
!
vrf VRF-A
 vni 100
!
vrf VRF-B
 vni 200
!
interface eth0
 ip address 10.0.12.2/30
!
router bgp 65002
 bgp router-id 10.0.12.2
 no bgp ebgp-requires-policy
 neighbor 10.0.12.1 remote-as 65001
 !
 address-family ipv4 unicast
  neighbor 10.0.12.1 activate
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.0.12.1 activate
  advertise-all-vni
 exit-address-family
!
router bgp 65002 vrf VRF-A
 bgp router-id 192.168.20.1
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 65002:100
  rt vpn both 65001:100
  export vpn
  import vpn
 exit-address-family
!
router bgp 65002 vrf VRF-B
 bgp router-id 192.168.40.1
 !
 address-family ipv4 unicast
  redistribute connected
  rd vpn export 65002:200
  rt vpn both 65001:200
  export vpn
  import vpn
 exit-address-family
!
line vty
!
