hostname peer
!
interface eth0
 ip address 10.0.30.2/30
!
ip route 172.16.3.0/24 Null0
!
router bgp 65003
 bgp router-id 10.0.30.2
 no bgp ebgp-requires-policy
 neighbor 10.0.30.1 remote-as 65000
 !
 address-family ipv4 unicast
  network 172.16.3.0/24
  neighbor 10.0.30.1 activate
 exit-address-family
!
line vty
!
