hostname router-c
!
interface eth0
 ip address 10.0.13.2/30
!
router bgp 65003
 bgp router-id 10.0.13.2
 no bgp ebgp-requires-policy
 no bgp network import-check
 neighbor 10.0.13.1 remote-as 65001
 !
 address-family ipv4 unicast
  network 10.0.0.0/8
  network 100.64.0.0/10
  network 172.16.0.0/12
  network 192.0.2.0/24
  network 192.168.0.0/16
  neighbor 10.0.13.1 activate
 exit-address-family
!
line vty
!
