hostname router-d
!
interface eth0
 ip address 10.0.24.2/30
!
interface eth1
 ip address 10.0.34.2/30
!
interface eth2
 ip address 192.168.4.1/24
!
router bgp 65004
 bgp router-id 10.0.24.2
 no bgp ebgp-requires-policy
 neighbor 10.0.24.1 remote-as 65002
 neighbor 10.0.34.1 remote-as 65003
 !
 address-family ipv4 unicast
  network 192.168.4.0/24
  neighbor 10.0.24.1 activate
  neighbor 10.0.34.1 activate
 exit-address-family
!
line vty
!
