hostname router-c
!
interface eth0
 ip address 10.0.23.2/30
!
interface eth1
 ip address 192.168.3.1/24
!
router bgp 65003
 bgp router-id 10.0.23.2
 no bgp ebgp-requires-policy
 neighbor 10.0.23.1 remote-as 65002
 !
 address-family ipv4 unicast
  neighbor 10.0.23.1 activate
  network 192.168.3.0/24
 exit-address-family
!
line vty
!
