hostname isp-backup
!
interface eth0
 ip address 10.0.13.2/30
!
router bgp 65003
 bgp router-id 10.0.13.2
 no bgp ebgp-requires-policy
 neighbor 10.0.13.1 remote-as 65001
 !
 address-family ipv4 unicast
  ! Also advertise a default route to the customer
  network 0.0.0.0/0
  neighbor 10.0.13.1 activate
  neighbor 10.0.13.1 next-hop-self
 exit-address-family
!
! Static default route to make BGP network statement work
ip route 0.0.0.0/0 Null0
!
line vty
!
