hostname router-b2
!
interface eth0
 ip address 10.0.20.3/24
!
interface eth1
 ip address 10.0.23.1/30
!
router bgp 65002
 bgp router-id 10.0.20.3
 no bgp ebgp-requires-policy
 neighbor 10.0.23.2 remote-as 65003
 !
 address-family ipv4 unicast
  neighbor 10.0.23.2 activate
  neighbor 10.0.23.2 next-hop-self
 exit-address-family
!
line vty
!
